---
collections:
  - name: community.network
    version: 8.0.0
  - name: community.general
  # network
  - name: cisco.ios
  - name: cisco.nxos
  - name: cisco.iosxr
  - name: ansible.netcommon
  - name: junipernetworks.junos
  - name: paloaltonetworks.panos
   # version 
  #Python Version The minimum python version for this collection is python 3.9.
  #- ansible-galaxy collection install paloaltonetworks.panos
